[package]
name = "starlight"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5.7"
num_cpus = "1.15.0"
pixels = "0.12.0"
rand = "0.8.5"
rayon = "1.7.0"
ultraviolet = "0.9.1"
winit = "0.28.3"
